### ISSUE TITLE
Early Request: Support react / nextjs

### ISSUE THREAD

**Issue by noxify** [fastrepl/canary#109]
Hi,

have seen your repo while searching for some inspiration how I could implement pagefind into my nextjs template.

Checked your docs and seems that you have created exactly what I need/want.

I'm using nextjs and the prod build is a static export which will be used to create the pagefind index.

I know your package is in an early stage but maybe there is an way to make the web components  available for react users, too.

I tried it already with a `dynamic import`( [Next Docu - Lazy Loading](https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading) ), but it seems it's currently not possible - Or I did something wrong?!

If you need more context or something else which could help, please let me know.

If it's already possible to use the web components in a react/next context, maybe you could provide some links, so I can give it a try.

Thanks a lot!

Regards,
Marcus

**Comment by noxify** [comment]
Ok, found a way to get a new error, but it seems it loads the component.

Example:

```ts
// file: /src/components/canary-search.tsx

"use client"

import dynamic from "next/dynamic"

export const CanaryRoot = ({ children }) => {
  const Component = dynamic(
    () =>
      import("@getcanary/web/components/canary-root.js").then((mod) => {
        const instance = new mod.CanaryRoot()
        return instance.render
      }),
    { ssr: false, loading: () => <>Loading...</> },
  )

  return (
    <>
      <Component>{children}</Component>
    </>
  )
}

```

But now I get the following error:

> TypeError: Cannot read properties of undefined (reading 'framework')

Based on the code: https://github.com/fastrepl/canary/blob/main/js/packages/web/src/components/canary-root.ts
I would assume that `starlight` is used a default 🤔

And it seems typescript can't find the correct types, getting also some type errors like:

> Property 'canary-root' does not exist on type 'JSX.IntrinsicElements'.ts(2339)

**Comment by yujonglee** [comment]
Hi @noxify - it's correct that the packages are in the early stage, but they are almost at version 1.0.0. So, it should work(anywhere, since it is web component :)). There might be a bug or some gotchas that I need to document.

If you can provide a simple repro, I will take a look and make it work.

Is this something you are working on? 
https://github.com/noxify/renoun-docs-template

**Comment by noxify** [comment]
Hi @yujonglee ,

thanks for the fast reply.

Yes, this is exactly the repo which  I use to implement pagefind.

I have some changes locally, will provide it after work in a dedicated branch.

**Comment by noxify** [comment]
Hi,

pushed my changes to the repo:

Here the commands to get started quickly :)
```
git clone git@github.com:noxify/renoun-docs-template.git
cd renoun-docs-template
git checkout pagefind
pnpm i
pnpm build
```

The `generate_pagefind` command is currently configured to save the index in the `out` directory:
```
"generate-pagefind": "pagefind --site out --output-path out/_next/static/chunks/pagefind",
```
( Ref: https://github.com/noxify/renoun-docs-template/blob/pagefind/package.json#L13 )

You can find the example component here:
https://github.com/noxify/renoun-docs-template/blob/pagefind/src/components/canary-search.tsx

It's imported/used in the homepage to make it easier to test :) 
https://github.com/noxify/renoun-docs-template/blob/pagefind/src/app/(home)/page.tsx#L26

I added some `@ts-expect-error` comments, to hide some errors in VSC, but while running `pnpm build`, you will get like

```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error

ReferenceError: HTMLElement is not defined
```

Hope this helps to reproduce, if not, please let me know what you need to reproduce/help.

Thanks a lot!

Regards,
Marcus

**Comment by yujonglee** [comment]
@noxify I appreciate your help on the repro. I managed to make it work, but there's few things to note & we need to sorted out.

https://github.com/yujonglee/renoun-docs-template/commit/590ece3fd9e4c50ec9f87057f95a55fc7227d9d8

## 1. `HTMLElement` error.

> ReferenceError: HTMLElement is not defined

This is because at the time of import, web component try to register itself. So we need to always import them inside `useEffect`.

```ts
useEffect(() => {
  void Promise.all([
    import("@getcanary/web/components/canary-root.js"),
    // ...
  ]).then(() => setLoaded(true))
}, [])
```

## 2. `@ts-expect-error`
This is because `React` is not aware of new tag provided by our web components. 
From `1.0.0-rc.0`,  I added this to each components, so  `@ts-expect-error` is not needed anymore.

https://github.com/fastrepl/canary/blob/39a62bc850434e8a7059a0348aa7404de9e675d2/js/packages/web/src/components/canary-root.ts#L53-L57

## 3. `pagefind` index generation

I know [someone](https://github.com/pmillspaugh/petemillspaugh.com/pull/16/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) make it work with command similar to yours, but below command works for me, and allow me to access pagefind assets at `localhost:<PORT>/pagefind/pagefind.js`.
```bash
"generate-pagefind": "pagefind --site out --output-path out/pagefind",
```

## 4. `pagefind` module import
I'm not sure why, but this fails even if `/pagefind/pagefind.js` is available.
(Please LMK if I'm missing something!)

https://github.com/fastrepl/canary/blob/39a62bc850434e8a7059a0348aa7404de9e675d2/js/packages/web/src/components/canary-provider-pagefind.ts#L49-L53

So I ended up something like this:
```ts
useEffect(() => {
  void import(
    // @ts-expect-error pagefind.js generated after build
    /* webpackIgnore: true */ "/pagefind/pagefind.js"
  ).then((m) => {
    // @ts-expect-error pagefind.js generated after build
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
    window.pagefind = m
  })
 // ...
}, [])
```

https://github.com/fastrepl/canary/blob/39a62bc850434e8a7059a0348aa7404de9e675d2/js/packages/web/src/components/canary-provider-pagefind.ts#L44-L49

---

All together, `canary-search.tsx` would be like this:
(Not that there's small API change with `canary-input` from `1.0.0`.

```ts
"use client"

import { useEffect, useState } from "react"

export const CanarySearch = () => {
  const [loaded, setLoaded] = useState(false)

  useEffect(() => {
    void import(
      // @ts-expect-error pagefind.js generated after build
      /* webpackIgnore: true */ "/pagefind/pagefind.js"
    ).then((m) => {
      // @ts-expect-error pagefind.js generated after build
      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
      window.pagefind = m
    })

    void Promise.all([
      import("@getcanary/web/components/canary-root.js"),
      import("@getcanary/web/components/canary-provider-pagefind.js"),
      import("@getcanary/web/components/canary-content.js"),
      import("@getcanary/web/components/canary-input.js"),
      import("@getcanary/web/components/canary-search.js"),
      import("@getcanary/web/components/canary-search-results.js"),
    ]).then(() => setLoaded(true))
  }, [])

  return (
    <>
      {loaded && (
        <canary-root>
          <canary-provider-pagefind>
            <canary-content>
              <canary-input slot="input"></canary-input>
              <canary-search slot="mode">
                <canary-search-results slot="body"></canary-search-results>
              </canary-search>
            </canary-content>
          </canary-provider-pagefind>
        </canary-root>
      )}
    </>
  )
}

```

**Comment by yujonglee** [comment]
## Serve `pagefind` index in dev

Currently, `/pagefind/pagefind.js` is not available when doing `pnpm run dev`, but available with `pnpm run build && pnpm run serve`. We had same problem with `docusaurus`, but it is fixed by below Webpack config.

https://github.com/fastrepl/canary/blob/39a62bc850434e8a7059a0348aa7404de9e675d2/js/packages/docusaurus-theme-search-pagefind/src/index.js#L19-L38

I guess this can be fixed in the same way, but I could not make it work at the moment.

**Comment by yujonglee** [comment]
## Explore better way to support `React` and `Nextjs`

I saw you were exploring with [@lit-labs/nextjs](https://www.npmjs.com/package/@lit-labs/nextjs), and there is also `@lit/react`. I am interested in providing `React wrapper` out of the box from `@getcanary/web/react` or `@getcanary/react`.

But the blocker is that `createcomponent` need `React` instance to be provided.  So I guess I can not just export **"React wrapped component"**.

https://lit.dev/docs/frameworks/react/#createcomponent

If you have some idea about this, please let me know.

**Comment by noxify** [comment]
Good morning in the morning :) 

how much did you spent on this? That's awesome!


> 1. HTMLElement error.

Using `useEffect` solves the problem - Thanks for taking the time to find a solution :) 

> 2. @ts-expect-error

can confirm, using `1.0.0-rc.0` solves the problem

> 3. pagefind index generation

It seems we have the same source ;). Used this as start point ( based on peters blog post )

> 4. pagefind module import
> and: Serve pagefind index in dev

I have splitted the code to have one `useEffect` to load the pagefind stuff and one to load the web components.
https://github.com/noxify/renoun-docs-template/blob/pagefind/src/components/canary-search.tsx

If we run into the `catch` we will set the `useMockProvider` to `true`.
Later we check the variable and loading the `canary-provider-mock` if needed.

Reason: I don't think it makes sense to try to mock the pagefind instance by our own. Your provided mock provider does exactly what I want - I have a usable component with some results. No need to mock all the sync/async functions without knowing how they are structured :) 

Previously, I used the code from peter where we fill `window.pagefind` with some mock data.
This will not work with the web compoents. 
We could spent more time into making it available by mocking it via `setupMiddlewares`, but for me, it's a "nice to have" feature.

> Explore better way to support React and Nextjs

Have to spend some time to get into the world of "lit elements" :) 
I understand the idea behind, but have to spend an afternoon to understand how it works :) 

I know that my company has also a "ui library" with different framework exports, checked what they are using --> it's https://github.com/BuilderIO/mitosis.

Was hoping that they also using lit, so we could use their repo as inspiration ;) 

Anyway... had the same idea with providing it via `@getcanary/web/react` or `@getcanary/react`.
But it seems that we have to manually create the `createComponent` wrapper for each element.

Maybe using a codemod ( jscodeshift? ) could help to generate it automagically, but not sure if/how this would work.

**Comment by noxify** [comment]
Updated the branch and added a draft to create the react components from the web components.

Rendering seems to work:
![image](https://github.com/user-attachments/assets/b5a1a256-cb7a-4da2-b433-b97161971c82)

I get also the available options from the web components:
![image](https://github.com/user-attachments/assets/dfb097a4-9ae2-43c1-8d13-f113334e1095)


if  there are no events in the components, the wrapper seems to be a low brainer to create.

Search Wrapper:
https://github.com/noxify/renoun-docs-template/blob/pagefind/src/components/canary-search-react.tsx

Web component wrapper:
https://github.com/noxify/renoun-docs-template/tree/pagefind/src/components/canary

-----

Unfortunately, I get now the following error in the log and also as error in the web:

```
 ReferenceError: HTMLElement is not defined
    at __webpack_require__ (/repo-root/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/repo-root/.next/server/webpack-runtime.js:33:42)
    at eval (./src/components/canary/root.tsx:7:98)
```

**Comment by noxify** [comment]
Checked also the nextjs example: https://github.com/lit/lit/tree/main/examples/nextjs-v14-app

I can't see any differences ( other than using a remote package to fetch the web components instead of using local ones ).
Maybe I missed something?

**Comment by noxify** [comment]
Good evening,

i was curious if the `HTMLElement is not defined` error is based on the canary components or if this is an general problem.
( just to get started to know where we have to change something ).

And I was able to reproduce the issue with a lightweight version of the renoun template and just the code from the provided nextjs example from lit ( copied the component code, installed the missing deps and changed the `tsconfig.json`).

The code can be found here: https://github.com/noxify/next-lit

----

Update: To make sure it's not a problem with my setup, I just installed the example add from lit - here I get the same result ( I just updated the deps )

---- 

Update 2:

Updated the "next-lit" repo and by using

```
const GreeterComponent = dynamic(
    () => import("@/components/lit/simple-greeter-react"),
    { ssr: false, loading: () => <p>Loading...</p> },
  )
```

The "HTMLElement..." error is gone and the component is interactive ( after the client is mounted and the component is loaded ).

Now let's see why it's working there and not with the canary components.

----

Update 3:
Another update - created a client component ( w/ `use client` ) and call the web component directly.
This time, I could import it directly into my `page.tsx` without getting the "HTMLElement..." error.

Based on this, for me, it seems that the problem could be the `createComponent` function.

Btw. the "HTMLElement is not defined" error is only a server problem. Tested it to build the site ( as static export ) and I was able to built the site.

But not sure how/if this would work if you do not export the site as html.

**Comment by yujonglee** [comment]
@noxify Thank you for the experiments!

Well, I don't have up-to-date information about recent changes in Next.js and RSC, so it may take some time for me to sort this all out. 

But in general, `HTMLElement is not defined` will happen when trying to import/use web components on the server, not in the browser. So, I think there's nothing from Canary's component side to do; it's about how we are using it.

Feel free to ping me on [Discord](https://discord.com/invite/Y8bJkzuQZU) too!

**Comment by noxify** [comment]
Good morning in the morning,

> So, I think there's nothing from Canary's component side to do; it's about how we are using it.

I fully agree with this. Based on that I now know:

* It's not a problem of the provided web components ( `@canary/web` )
* I'm not sure if this required to provide the web components via the `createComponent` helper
  * Reason: It does some magic which you can't control and based on the tests we did here, it seems it's not necessary 
*  Providing the types from the lit element to the JSX Types would help to use it directly
   ( Example: https://github.com/noxify/next-lit/blob/main/src/components/lit/simple-greeter.ts#L62-L70 )
* I think it could be enough to add a  new page to the `Integration`section to support react/nextjs
  * We could use `useEffect`
  * We could create our own client component which imports the component from `@getcanary/web` 

If your plan is to support different frameworks ( e.g. svelte / angular / webcomponents / react / <framework> ), maybe it could be easier to switch to something which will generate the "native" code for you.

Spent a hour yesterday evening with mitosis ( [Playground](https://mitosis.builder.io/playground) ) and it looks promising.

* Have seen a fetch example in their starter kit, so async requests should be possible ( e.g. to load pagefind )
* For the styling, it seems that it makes more sense to have a shared css/scss file for the styling 
  ( instead of having a `static styles`as you have now )
* The generated code from my simple example looks good, but not sure if this is the case if you have more complexity
* Requires some ( / a full? ) refactoring of all components ( if you plan to use it )
* I think it will produce at least one breaking change - so it could be something for V2 or later
* I haven't checked alternatives

**Comment by noxify** [comment]
Will close this issue for now - We found a solution which works for me :)
