### ISSUE TITLE
Add transition on canary-modal open/close

### ISSUE THREAD

**Issue by yujonglee** [fastrepl/canary#132]
## Current modal behavior

https://storybook.getcanary.dev/?path=/story/public-components-canary-modal--default

## Related files

https://github.com/fastrepl/canary/blob/main/js/packages/web/src/components/canary-modal.ts
https://github.com/fastrepl/canary/blob/main/js/packages/web/src/components/canary-dialog.ts

should accept `transition` attribute to enable it.
use css-variables to configure the transition.

## Reference

- searchbar in https://nextjs.org/

**Comment by akhilender-bongirwar** [comment]
@yujonglee, I am interested in working on this issue. Could you provide the steps to run the web app locally so I can test the changes?

**Comment by yujonglee** [comment]
@akhilender-bongirwar 

Sure.
https://github.com/fastrepl/canary/blob/main/CONTRIBUTING.md#getcanaryweb

**Comment by akhilender-bongirwar** [comment]
> @akhilender-bongirwar
> 
> Sure. https://github.com/fastrepl/canary/blob/main/CONTRIBUTING.md#getcanaryweb

Thanks for updating it : )

**Comment by animeshd9** [comment]
Can i work on the issue @yujonglee ?. Since you have open the issue 21 minutes ago.
