### ISSUE TITLE
Present pagefind plugin as a theme

### ISSUE THREAD

**Issue by bohyunjung** [fastrepl/canary#49]
Hi, I found this repo from https://github.com/facebook/docusaurus/pull/10345, and I'm happy to see a new option for searching on Docusaurus.

There are two things I'd like to suggest regarding `@getcanary/docusaurus-pagefind`. (before things get too complicated to change!)

### Present it as a theme

I use https://github.com/easyops-cn/docusaurus-search-local, which was initially a plugin but was changed to a theme. Please refer to https://github.com/facebook/docusaurus/issues/6488#issuecomment-1024124096 and I think it's worth following the precedents.

### Rename it

Suppose you agree with deploying it as a theme - While the name of `docusaurus-pagefind` is straightforward, giving a name like `docusaurus-theme-search-pagefind` might enhance the branding of the theme. These are some examples I referred to the naming style.

* [docusaurus-theme-search-typesense](https://github.com/typesense/docusaurus-theme-search-typesense)
* [@docusaurus/theme-search-algolia](https://docusaurus.io/docs/next/api/themes/@docusaurus/theme-search-algolia)
* [@markprompt/docusaurus-theme-search](https://github.com/markprompt/markprompt-js/tree/main/packages/docusaurus-theme-search)

**Comment by yujonglee** [comment]
https://docusaurus.io/docs/using-plugins#using-themes

> From the consumer perspective, the themes and plugins entries are interchangeable when installing and configuring a plugin. The only nuance is that themes are loaded after plugins, and it's possible for a theme to override a plugin's default theme components.

**Comment by yujonglee** [comment]
143b0bddb60040ad3e9d819997a06276bfb2cb6c
